version: '3.1'

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=edu-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - .docker/dev_data:/var/lib/postgresql
